//Relational and Comparative operators:
console.log(5>4)
console.log(5<4)
console.log(5>=4)
console.log(5<=4)
console.log(4<=4)
console.log(3<=4)
console.log(4=="4")
console.log(4==="4")
console.log(4!="5")
console.log(4!=="5")